sonar.projectKey=Tiniiz_InfoSystem
sonar.organization=tiniiz
sonar.host.url=https://sonarcloud.io

sonar.projectName=InfoSystem
sonar.projectVersion=1.0

sonar.language=java
sonar.sourceEncoding=UTF-8

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.exclusions=Kursovaya/**,build/**,gradle/**,**/*.html,**/*.xml

sonar.java.binaries=build/classes/java/main
